### ISSUE TITLE
Grammar rules?

### ISSUE THREAD

**Issue by simonrenger** [ninkibah/TseePlusPlus#3]
Are we following the German grammar or C++ standard?

I am asking because then for example if we were to follow the German Grammar all Nouns need to be with capital letters! Besides stuff like "sentences" would need to have a `_` between them. Do we also include articles? How far shall this go....

**Comment by ninkibah** [comment]
@simonrenger yesterday I tweeted about adding the following #defines:
```c++
#define der auto
#define die auto
#define das auto

das Buck = "Der Bibel";
die Summe = 0;
der Tisch = Personentabelle{};
```

**Comment by ninkibah** [comment]
I updated the library and added a section in the README.md to support the above code.
